### ISSUE TITLE
Motorcontroller in de buggy vinden

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#10]

**Comment by kew10** [comment]
![9fc4a2c9-e778-4bc1-b2be-30d3135fffff](https://user-images.githubusercontent.com/45833587/76960303-766b5300-691b-11ea-8cce-e6d6b087ed56.jpg)
![90d4d8c6-e8cd-4381-b84e-1cac102b935d](https://user-images.githubusercontent.com/45833587/76960331-8125e800-691b-11ea-8405-8bd44688d42c.jpg)

**Comment by Fre101** [comment]
Dit ticket kunnen we afsluiten! 
Bedankt voor de afbeeldingen.
