### ISSUE TITLE
KickOff_Presentatie voorstellen

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#11]

**Comment by KingAbad** [comment]
[KickOff_Presentatie_Abad_Sethi.pptx](https://github.com/KingAbad/Autonomous_Cart_2/files/4348916/KickOff_Presentatie_Abad_Sethi.pptx)

**Comment by Fre101** [comment]
Kan iedereen zijn presentatie nog uploaden in deze ticket?
Dan kunnen we deze afsluiten.

**Comment by Fre101** [comment]
Dit ticket kan naar done.

**Comment by kew10** [comment]
Metehan, Ali Uplaud jullie presentaties!
