### ISSUE TITLE
Jetson Nano kan over tcp/ip communiceren met de PLC

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#15]

**Comment by KingAbad** [comment]
Begonnen met Jetson Nano communicatie te regelen over TCP/IP met PLC server

**Comment by KingAbad** [comment]
Ik ga eerst ervoor zorgen dat ik over SSH met de Jetson Nano kan communiceren

**Comment by KingAbad** [comment]
IP adres Jetson Nano gevonden met AngryIpScanner

![afbeelding](https://user-images.githubusercontent.com/55444413/78081632-48711e80-73b1-11ea-85b7-811e1ef5c64c.png)

**Comment by KingAbad** [comment]
IP gevonden en communicatie gestart met PuTTY

![afbeelding](https://user-images.githubusercontent.com/55444413/78081704-7b1b1700-73b1-11ea-91a3-a24c52ab5eba.png)

**Comment by KingAbad** [comment]
Succesvolle verbinding met de Jetson Nano over SSH

![afbeelding](https://user-images.githubusercontent.com/55444413/78081807-bc132b80-73b1-11ea-9179-95145c068c9a.png)

**Comment by KingAbad** [comment]
Nu ga ik beginnen met het schrijven van een Client-Side python script om de Jetson Nano te kunnen verbinden met de PLC server ==> deze is er nog niet

**Comment by KingAbad** [comment]
Ik heb om te testen een Server en Client python script geschreven om berichten naar elkaar te kunnen sturen en het werkt

![afbeelding](https://user-images.githubusercontent.com/55444413/78083367-853f1480-73b5-11ea-960c-cdd4fcad0a17.png)

**Comment by KingAbad** [comment]
Omdat de PLC Server nog niet volledig klaar is help ik nu degene die daarvoor verantwoordelijk zijn

![afbeelding](https://user-images.githubusercontent.com/55444413/78083772-c08e1300-73b6-11ea-8fce-1f33c874a77f.png)

**Comment by KingAbad** [comment]
PLC Server Volledig klaar maar communicatie werkt niet

**Comment by KingAbad** [comment]
Eerstefout gevonden: Niet juiste Poort en Ip adres ingegeven

**Comment by KingAbad** [comment]
Tweedefout gevonden: Firewalls stonden aan voor outbound connecties. Dus alle firewalls inclusies windows defender uitgeschakeld

![afbeelding](https://user-images.githubusercontent.com/55444413/78084005-604ba100-73b7-11ea-93d9-4444f9ec8ab8.png)

Een nieuwe outbound rule "NetworkProgramming" aangemaaktt om alle outbound connecties door te laten

![afbeelding](https://user-images.githubusercontent.com/55444413/78084135-ba4c6680-73b7-11ea-988a-09d44b1a6a27.png)

**Comment by KingAbad** [comment]
Derdefout: Portmapping moest gedaan worden voor de Jetson Nano om over andere netwerken te kunnen verbinden

![afbeelding](https://user-images.githubusercontent.com/55444413/78084612-f6cc9200-73b8-11ea-825f-34633360ca44.png)

**Comment by KingAbad** [comment]
Alle fouten en bijkomende errors opgelost en bij deze communicatie Jetson Nano Client met PLC Server werkt perfect 

zie video demo

[Demo_Com_PLC_Jetson.zip](https://github.com/KingAbad/Autonomous_Cart_2/files/4412055/Demo_Com_PLC_Jetson.zip)

**Comment by KingAbad** [comment]
Hier is nog een demo waarop je kan zien dat ik de outputs kan aansturen via afgesproken commando's met het PLC team

https://github.com/KingAbad/Autonomous_Cart_2/files/4412165/commandos_VerlichtingToggelen.zip
