### ISSUE TITLE
Onderzoek motorcontroller

### ISSUE THREAD

**Issue by KingAbad** [KingAbad/Autonomous_Cart_2#2]

**Comment by kew10** [comment]
test

**Comment by meto51** [comment]
poort onder de dash gevonden om controller in te lezen

**Comment by meto51** [comment]
gemeten of de kabels met elkaar verbonden zijn(die zijn verbonden).

**Comment by meto51** [comment]
deel van motorcontroller geschreven

**Comment by kew10** [comment]
word doc. aangemaakt voor de documentatie over het project. Opmaak toegevoegd.

**Comment by meto51** [comment]
![Untitled Diagram(5)](https://user-images.githubusercontent.com/48825146/77473953-8ea90980-6e16-11ea-8975-37b5eb473d47.png)
