### ISSUE TITLE
Afspreken met PLC team: Welke communicatieprotocol gebruikt gaat worden voor communicatie tussen Jetson Nano (client) en PLC (server)

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#29]

**Comment by KingAbad** [comment]
Na een korte overleg met enkele verantwoordelijke voor de communicatie(Jetson-PLC) zijn we samen tot de  beslissing gekomen dat de communicatie tussen Jetson Nano (client en PLC (server) gaat gebeuren met  **TCP/IP**
