### ISSUE TITLE
DC to DC converter voor de componenten op de PCB

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#30]

**Comment by kew10** [comment]
Dc to dc converter gevonden, 48 v ==> 5v.  € 30,54 inc btw en verzendingskosten

https://benl.rs-online.com/web/p/isolated-dc-dc-converters/8764721?cm_mmc=BE-PLA-DS3A-_-google-_-PLA_BE_NL_Power_Supplies_And_Transformers-_-Dc-Dc_Converters%7CIsolated_Dc-Dc_Converters-_-PRODUCT_GROUP&matchtype=&aud-813230962291:pla-392403034239&gclid=Cj0KCQjwyPbzBRDsARIsAFh15JY0gDjjfcPLHFYjZR0Di4BTrchmpl1aQ-khgeWBZBMHZWeejL9EBwIaAt1MEALw_wcB&gclsrc=aw.ds

**Comment by Fre101** [comment]
Dit was een goede eerste keuze, maar heb nog heel wat andere gevonden ondertussen.

**Comment by Fre101** [comment]
Deze kan gesloten worden. Ik update jullie later over alle keuzes.
