### ISSUE TITLE
Schema elektronica bordje opstellen.

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#37]

**Comment by kew10** [comment]
Voorlopig schema ontwikkelt voor elektronica bordje(30/3).


![elek1](https://user-images.githubusercontent.com/45833587/78051593-35912680-737e-11ea-9090-3699504809b3.PNG)

[Kazim-Layout1 (1).pdf](https://github.com/KingAbad/Autonomous_Cart_2/files/4410354/Kazim-Layout1.1.pdf)

**Comment by Fre101** [comment]
Dit is inderdaad een eerste schema, maar het zal zeker nog veranderen en toevoegingen krijgen.

**Comment by Fre101** [comment]
Ik zal deze issue afsluiten, maar je zal waarschijnlijk nieuwe issues aanmaken voor dit af te werken.
