### ISSUE TITLE
Paper klaarmaken voor de productowner

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#4]

**Comment by KingAbad** [comment]
Meegeholpen aan voorblad van documentatie

**Comment by kew10** [comment]
Docx bestand aangemaakt voor de documentatie van het project. Hierbij de opmaak klaargemaakt.

**Comment by KingAbad** [comment]
Componentenlijst opgesteld

**Comment by kew10** [comment]
[Documentatie.docx](https://github.com/KingAbad/Autonomous_Cart_2/files/4366266/Documentatie.docx)

**Comment by Fre101** [comment]
Dit is al een goed begin.
