### ISSUE TITLE
Een flowdiagram van de technische issues opstellen

### ISSUE THREAD

**Issue by meto51** [KingAbad/Autonomous_Cart_2#40]

**Comment by meto51** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/48825146/78087133-57130200-73c0-11ea-90be-7b78c7010e06.png)

**Comment by KingAbad** [comment]
Mooi gedaan Metehan!
Alleen heb ik enkele aanpassingen gemaakt zodat het klopt voor de huidige situatie.


![afbeelding](https://user-images.githubusercontent.com/55444413/78100050-07463200-73e4-11ea-9053-90ead87d8f4f.png)
