### ISSUE TITLE
Takenverdelen

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#9]

**Comment by kew10** [comment]
Ik heb een teammeeting georganiseerd met onze product owner (Frederik) om de taken te verdelen. We hebben onderschat hoeveel wij in een sprint zouden kunnen afmaken, waardoor niet iedereen genoeg had om te doen voor dit sprint. Voor volgende sprint moeten we meer realistische goals opstellen. Ali gaat voorwerken en proberen leds aan te sturen adv sensoren. Ik ga de backlog updaten/ project beschrijving opstellen / metehan help met documentatie motor controller.

**Comment by ALi-Natiq** [comment]
ik ga de RGB leds adv ultrasonic sensor aanpakken. dus eerst ga ik proberen om de ultrasonic sensor te programmeren gebruik maken van raspberry pi en daarna ga ik zijn signalen gebruiken om de RGB leds aan te sturen.

**Comment by meto51** [comment]
Onderzoek naar motorcontroller en de tekst uitgetypt in een document

**Comment by meto51** [comment]
Helpen bij communicatie tussen Jetson Nano en PLC

**Comment by kew10** [comment]
iedereen moet helpen om issues bij te voegen!

**Comment by ALi-Natiq** [comment]
ultrasonic is succesvol geprogrammeerd met de pi

**Comment by ALi-Natiq** [comment]
Er moet verder de RGB leds kunnen sturen gebruik maken van ultrasonic sensor.

**Comment by KingAbad** [comment]
Voor iedereen was het duidelijk na de meeting van 19/03/2020 wat hij moest doen.
